### ISSUE TITLE
Train on custom dataset using pre-trained model

### ISSUE THREAD

**Issue by meetdave06** [YangZeyu95/unofficial-implement-of-openpose#6]
Hi,

Could you let me know how to train the model on custom dataset using pre-trained COCO model using transfer learning?

**Comment by YangZeyu95** [comment]
You can fine-tune the pre-trained models by 
`python train.py --continue_training True --checkpoint_path <your dir contains the pretrained model> --train_vgg True --annot_path <dir contains annotation file> --img_path <dir contains images>`
And make dir structure follow 'Training' part of [README](https://github.com/YangZeyu95/unofficial-implement-of-openpose/blob/master/README.md) .
Btw, that should be fine-tune rather than transfer learning, if you really mean transfer learning, there would be a lot to be modified. Such as delete and add some layers you like at the end of the network.

**Comment by meetdave06** [comment]
@YangZeyu95  That's really helpful. Thanks
